name: Build Android APK

on:
  push:
    branches:
      - mobile
  pull_request:
    branches:
      - mobile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            python3 \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libgstreamer1.0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            libsqlite3-dev \
            sqlite3 \
            libbz2-dev \
            libssl-dev \
            libffi-dev \
            zip \
            unzip \
            autoconf \
            libtool \
            pkg-config

      - name: Install Buildozer and Dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install buildozer cython

      - name: Build with Buildozer
        run: |
          # Accepting SDK license is crucial
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
